Added option to disable motors on cancel
mainsail-crew/mainsail-config pull request #23
Opened 2023-09-10 22:37 UTC by VoltexRB

Added variable to _CLIENT_VARIABLE to select if motors should be disabled after cancelling a print and added if statement to evaluate variable in CANCEL_PRINT.

Note: I am tired of having to add this on every update, I can't remember a single time I cancel a print and not disable motors. its an optional change.

2023-09-11 05:42 UTC, meteyou approved these changes

2023-10-17 06:59 UTC, zellneralex reviewed
See my note about the parameter location. The Readme.md would also need to be enhanced.
Change the examples to include your Parameter. 
Add a section to explain what it does at the bottom.

2023-10-17 06:59 UTC, zellneralex commented on client.cfg
> +#variable_park_at_cancel         : False ; allow to move the toolhead to park while execute CANCEL_PRINT [True/False]
I do not like that you splitt the poark canclel paramter. Please place your parameter before line 38

2023-10-17 07:02 UTC, zellneralex requested changes
See my note about the parameter location. The Readme.md would also need to be enhanced.
Change the examples to include your Parameter.
Add a section to explain what it does at the bottom.

2023-10-19 15:20 UTC, alcor6502 commented
Thanks to [VoltexRB](https://github.com/VoltexRB), I come up with a broader solution which can accomodate other needs not only to just disable the motors.
[Added option to run a custom macro on CANCEL_PRINT #25](https://github.com/mainsail-crew/mainsail-config/pull/25)

2023-10-19 16:51 UTC, VoltexRB commented
Better to use pull request by alcor6502

2023-10-19 16:51 UTC, closed without merging